In [14]:
import pandas as pd
import numpy as np

In [15]:
traindata = pd.read_csv('C:/Users/Teju/Downloads/Datasets and details/train.csv')
testdata  = pd.read_csv('C:/Users/Teju/Downloads/Datasets and details/test.csv')

In [16]:
testdata.shape

(173, 14)

In [17]:
traindata.head().info

<bound method DataFrame.info of    ID     crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0   1  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1   2  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2   4  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
3   5  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
4   7  0.08829  12.5   7.87     0  0.524  6.012  66.6  5.5605    5  311   

   ptratio   black  lstat  medv  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     18.7  394.63   2.94  33.4  
3     18.7  396.90   5.33  36.2  
4     15.2  395.60  12.43  22.9  >

In [27]:
traindata.describe()

ID        crim          zn       indus        chas         nox  \
count  333.000000  333.000000  333.000000  333.000000  333.000000  333.000000   
mean   250.951952    3.360341   10.689189   11.293483    0.060060    0.557144   
std    147.859438    7.352272   22.674762    6.998123    0.237956    0.114955   
min      1.000000    0.006320    0.000000    0.740000    0.000000    0.385000   
25%    123.000000    0.078960    0.000000    5.130000    0.000000    0.453000   
50%    244.000000    0.261690    0.000000    9.900000    0.000000    0.538000   
75%    377.000000    3.678220   12.500000   18.100000    0.000000    0.631000   
max    506.000000   73.534100  100.000000   27.740000    1.000000    0.871000   

               rm         age         dis         rad         tax     ptratio  \
count  333.000000  333.000000  333.000000  333.000000  333.000000  333.000000   
mean     6.265619   68.226426    3.709934    9.633634  409.279279   18.448048   
std      0.703952   28.133344    1.981123    8.742174  170.841988    2.151821   
min      3.561000    6.000000    1.129600    1.000000  188.000000   12.600000   
25%      5.884000   45.400000    2.122400    4.000000  279.000000   17.400000   
50%      6.202000   76.700000    3.092300    5.000000  330.000000   19.000000   
75%      6.595000   93.800000    5.116700   24.000000  666.000000   20.200000   
max      8.725000  100.000000   10.710300   24.000000  711.000000   21.200000   

            black       lstat        medv  
count  333.000000  333.000000  333.000000  
mean   359.466096   12.515435   22.768769  
std     86.584567    7.067781    9.173468  
min      3.500000    1.730000    5.000000  
25%    376.730000    7.180000   17.400000  
50%    392.050000   10.970000   21.600000  
75%    396.240000   16.420000   25.000000  
max    396.900000   37.970000   50.000000

In [19]:
features = traindata.columns

In [20]:
traindata[features].isnull().any()

ID         False
crim       False
zn         False
indus      False
chas       False
nox        False
rm         False
age        False
dis        False
rad        False
tax        False
ptratio    False
black      False
lstat      False
medv       False
dtype: bool

In [21]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(random_state=1)
model2 = RandomForestRegressor(random_state=2)

In [9]:
""""train_y = traindata.iloc[0:250,14]
train_X = traindata.iloc[0:250,0:14]
test_X = traindata.iloc[251:332,0:14]
test_y = traindata.iloc[251:332,14]"""

'"train_y = traindata.iloc[0:250,14]\ntrain_X = traindata.iloc[0:250,0:14]\ntest_X = traindata.iloc[251:332,0:14]\ntest_y = traindata.iloc[251:332,14]'

In [29]:
featuresinm = ['crim','chas','nox','rm','age','dis','rad','tax','ptratio','lstat']
model.fit(traindata.iloc[:,0:14],traindata['medv'])
model2.fit(traindata.iloc[:,0:14],traindata['medv'])

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=2, verbose=0, warm_start=False)

In [30]:
model.feature_importances_
model2.feature_importances_

array([1.29547164e-02, 5.72246490e-02, 1.04501385e-03, 6.51667262e-03,
       3.43009884e-04, 1.35170765e-02, 4.70121595e-01, 1.42697754e-02,
       4.42360680e-02, 4.68410712e-03, 1.19058936e-02, 1.07060382e-02,
       1.25215852e-02, 3.39953799e-01])

As this dataset is from a competition there was no result

In [31]:
#model.score(testdata[featuresinm],testdata['medv'])
#model2.score(testdata[featuresinm],testdata['medv'])


In [32]:
traindata.columns

Index(['ID', 'crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad',
       'tax', 'ptratio', 'black', 'lstat', 'medv'],
      dtype='object')

In [34]:
y=model.predict(testdata)
y2 = model2.predict(testdata)

In [35]:
from sklearn.svm import SVR
from sklearn.model_selection import GridSearchCV
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler as ss

traindata[featuresinm].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 333 entries, 0 to 332
Data columns (total 10 columns):
crim       333 non-null float64
chas       333 non-null int64
nox        333 non-null float64
rm         333 non-null float64
age        333 non-null float64
dis        333 non-null float64
rad        333 non-null int64
tax        333 non-null int64
ptratio    333 non-null float64
lstat      333 non-null float64
dtypes: float64(7), int64(3)
memory usage: 26.1 KB


In [36]:
c = [0.05,0.1,0.5,1,10]
gamma = [0.01,0.1,0.5]
kern = ['rbf','linear']
params = {'C':c,'gamma':gamma,'kernel':kern}
svm = GridSearchCV(SVR(),params)


In [37]:
#svm = SVR(kernel = 'rbf',gamma = 0.1, C = 1 )
svm.fit(traindata.iloc[:,0:14], traindata['medv'])


GridSearchCV(cv=None, error_score='raise',
       estimator=SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': [0.05, 0.1, 0.5, 1, 10], 'gamma': [0.01, 0.1, 0.5], 'kernel': ['rbf', 'linear']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [39]:
y3=svm.predict(testdata)

In [43]:
submissionsvm = pd.DataFrame({'ID':testdata['ID'],'medv':y3})
submissionsvm.to_csv('submissionsvm.csv',index= False)

In [41]:
y3

array([28.0948031 , 25.22178698, 18.14218854, 10.56974839, 18.43132833,
       17.83150888, 20.1958871 , 16.46901669, 14.95758905, 16.74403507,
       19.29673086, 20.3264076 ,  8.65156405, 15.1709793 , 23.88027715,
       22.59374254, 24.07353578, 27.19066292,  8.062632  , 27.32828011,
       22.37531344, 24.01064685, 21.29841227, 21.36595205, 19.4603447 ,
       21.77753261, 25.96666622, 26.04413507, 27.10554797, 26.57154573,
       30.37861621, 30.96777973, 28.40225916, 20.72952268, 18.03471011,
       20.54814461, 19.60168814, 19.11187936, 19.31554645, 21.10081093,
       14.85694498, 19.3288589 , 19.7431646 , 16.54273761, 12.58379038,
       15.01929601, 12.6072749 , 18.67453518, 22.06587196, 22.7672237 ,
       19.96619939, 29.60968149, 32.98660004, 23.77501337, 22.22477393,
       23.54270135, 30.91193459, 37.1416743 , 33.44359871, 31.79353682,
       30.11814108, 34.53462361, 16.98922161, 13.89539821, 18.41196387,
       19.75196121, 23.69820339, 25.6038682 , 20.54842805, 25.07

In [44]:
y2

array([33.15, 24.71, 16.59, 15.33, 17.45, 18.93, 19.73, 15.65, 14.63,
       18.68, 18.29, 19.91, 14.19, 15.1 , 20.29, 20.19, 21.79, 29.95,
       17.47, 25.78, 21.27, 23.61, 20.73, 21.65, 21.39, 20.59, 24.31,
       22.43, 22.65, 28.1 , 45.52, 46.11, 30.48, 19.67, 18.46, 20.67,
       18.09, 17.36, 19.35, 20.38, 15.9 , 20.02, 19.42, 16.69, 15.01,
       14.15, 15.46, 14.34, 19.77, 20.21, 17.2 , 33.12, 45.06, 21.34,
       22.61, 23.47, 30.5 , 47.23, 32.06, 30.7 , 32.3 , 40.12, 21.07,
       18.58, 19.07, 20.98, 25.  , 25.89, 18.32, 22.32, 29.77, 40.88,
       31.66, 33.58, 24.32, 26.77, 21.79, 21.23, 20.28, 32.66, 21.68,
       20.2 , 37.74, 46.4 , 34.13, 30.47, 44.16, 21.53, 20.81, 30.57,
       34.35, 31.38, 24.52, 47.3 , 23.51, 26.79, 34.8 , 22.48, 27.56,
       24.3 , 31.22, 28.07, 28.82, 22.74, 25.08, 21.62, 24.17, 22.62,
       19.94, 24.39, 23.89, 19.12, 21.47, 21.8 , 20.34, 21.59, 20.53,
       23.78, 26.35, 29.21, 21.69, 22.34, 20.66, 18.38, 43.37, 38.48,
       34.38, 12.86,

In [45]:
y

array([33.37, 24.22, 18.03, 13.84, 19.58, 20.28, 19.51, 15.37, 16.29,
       17.3 , 18.32, 22.51, 18.34, 15.25, 21.69, 21.52, 21.73, 30.73,
       15.51, 25.02, 22.13, 23.55, 21.59, 20.9 , 20.82, 21.41, 23.52,
       21.63, 22.82, 28.95, 44.48, 45.76, 28.51, 20.52, 18.03, 22.54,
       18.37, 17.84, 19.35, 19.37, 15.27, 19.45, 19.95, 17.44, 16.23,
       14.16, 15.12, 14.88, 21.81, 20.77, 18.81, 28.92, 47.1 , 22.07,
       18.2 , 23.62, 29.04, 47.38, 32.7 , 31.18, 32.71, 44.25, 21.14,
       17.81, 19.5 , 21.12, 23.86, 24.13, 20.  , 22.6 , 27.45, 44.6 ,
       35.68, 32.99, 23.8 , 26.95, 21.96, 20.59, 21.71, 31.51, 21.4 ,
       20.  , 43.55, 44.58, 31.53, 28.11, 42.61, 21.87, 20.79, 31.68,
       34.59, 30.95, 24.18, 47.39, 23.07, 26.14, 35.14, 21.4 , 27.74,
       24.  , 34.1 , 30.17, 30.83, 21.94, 23.5 , 22.18, 24.36, 23.53,
       18.54, 24.85, 24.79, 19.51, 19.38, 21.01, 20.63, 20.31, 18.85,
       20.8 , 26.69, 29.96, 19.34, 23.  , 21.66, 19.15, 41.84, 42.98,
       34.15, 11.92,